INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (1,'Rántotta (3 tojásból)',228,1,20,15);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (2,'Rántotta (3 tojásból)',304,20,27,1);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (3,'Tükörtojás (3 tojásból)',228,1,20,15);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (4,'Tükörtojás (4 tojásból)',304,20,27,1);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (5,'Zabkása  (~100 gramm zabból)',130,19,5,4);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (6,'Rozskenyér szendvics (2 szelet)',405,15,9,6);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (7,'Banánturmix',290,8,32,15);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (8,'Nyerskoszt (200g paradicsom + 130g sárgarépa + 330g retek)',172,25,8,0);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (9,'Bundáskenyér (Light, kevés olaj, teljes kiőrlésű kenyér)',453,40,35,17);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (10,'Chiamag puding',215,34,5,8);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (11,'Chiamag puding',262,15,20,15);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (12,'Rántotta (4 tojásól)',304,2,27,17);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (13,'Tükörtojás (3 tojásból)',228,1,20,15);
INSERT INTO "breakfast" ("ID","name","calories","carbs","proteins","fats") VALUES (14,'Rántotta (4 tojásból)',304,2,27,17);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (1,NULL,0,NULL,NULL,NULL);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (2,'körözöttes kenyér',273,11,40,8);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (3,'alma',78,1,17,0);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (4,'körte',101,1,1,0);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (5,'banán',105,1,24,0);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (6,'narancs (2 db)',124,2,24,0);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (7,'mandarin (6db)',280,4,60,2);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (8,'protein szelet',233,18,28,7);
INSERT INTO "brunch" ("ID","name","calories","carbs","proteins","fats") VALUES (9,'gyümölcs turmix (~350g gyümölcsel)',141,2,32,1);
INSERT INTO "lunch" ("ID","name","calories","carbs","proteins","fats") VALUES (1,'lunch 1',500,NULL,NULL,NULL);
INSERT INTO "lunch" ("ID","name","calories","carbs","proteins","fats") VALUES (2,'lunch 2',600,NULL,NULL,NULL);
INSERT INTO "lunch" ("ID","name","calories","carbs","proteins","fats") VALUES (3,'lunch 3',800,NULL,NULL,NULL);
INSERT INTO "lunch" ("ID","name","calories","carbs","proteins","fats") VALUES (4,'lunch 4',1000,NULL,NULL,NULL);
INSERT INTO "lunch" ("ID","name","calories","carbs","proteins","fats") VALUES (5,NULL,0,NULL,NULL,NULL);
INSERT INTO "lunch" ("ID","name","calories","carbs","proteins","fats") VALUES (6,NULL,0,NULL,NULL,NULL);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (1,'körözöttes kenyér',273,11,40,8);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (2,'alma',78,1,17,0);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (3,'körte',101,1,1,0);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (4,'banán',105,1,24,0);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (5,'narancs (2 db)',124,2,24,0);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (6,'mandarin (6db)',280,4,60,2);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (7,'protein szelet',233,18,28,7);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (8,'gyümölcs turmix (~350g gyümölcsel)',141,2,32,1);
INSERT INTO "afternoon" ("ID","name","calories","carbs","proteins","fats") VALUES (9,'Natur kefir',59,3,3,4);